set_location_assignment PIN_A11 -to led[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[0]
set_location_assignment PIN_A10 -to led[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[1]
set_location_assignment PIN_B10 -to led[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[2]
set_location_assignment PIN_C10 -to led[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[3]
set_location_assignment PIN_C9 -to led[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[4]
set_location_assignment PIN_C8 -to led[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[5]
set_location_assignment PIN_B8 -to led[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[6]
set_location_assignment PIN_A8 -to led[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to led[7]
