create_ip -module_name GTWizard0 -vendor xilinx.com -library ip -name gtwizard_ultrascale -version 1.7

set GTWIZARD0_PROPERTIES {}

set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
    CONFIG.preset GTH-HDMI

    CONFIG.TX_USER_DATA_WIDTH 40
    CONFIG.TX_INT_DATA_WIDTH 40

    CONFIG.RX_USER_DATA_WIDTH 40
    CONFIG.RX_INT_DATA_WIDTH 40

    CONFIG.FREERUN_FREQUENCY 10.0

    CONFIG.CHANNEL_ENABLE { X0Y19 X0Y18 X0Y17 X0Y16 }
    CONFIG.TX_MASTER_CHANNEL X0Y17
    CONFIG.RX_MASTER_CHANNEL X0Y17

    CONFIG.TX_REFCLK_SOURCE { X0Y19 clk0 X0Y18 clk0 X0Y17 clk0 X0Y16 clk0 }
    CONFIG.RX_REFCLK_SOURCE { X0Y19 clk0 X0Y18 clk0 X0Y17 clk0 X0Y16 clk0 }

    CONFIG.LOCATE_TX_USER_CLOCKING CORE
    CONFIG.LOCATE_RX_USER_CLOCKING CORE

    CONFIG.ENABLE_OPTIONAL_PORTS {
        gtrefclk00_in
        gtrefclk01_in

        qpll0outclk_out
        qpll0outrefclk_out
        qpll1outclk_out
        qpll1outrefclk_out
    }
}]

switch "$RESOLUTION@$REFRESH_RATE" {
    "1920x1080@30" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 0.7425
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 148.5

            CONFIG.RX_LINE_RATE 0.7425
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 148.5
        }]
    }
    "2560x1440@30" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 1.21584
            CONFIG.TX_PLL_TYPE QPLL1
            CONFIG.TX_REFCLK_FREQUENCY 121.584

            CONFIG.RX_LINE_RATE 1.21584
            CONFIG.RX_PLL_TYPE QPLL1
            CONFIG.RX_REFCLK_FREQUENCY 121.584
        }]
    }
    "1920x1080@60" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 1.485
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 148.5

            CONFIG.RX_LINE_RATE 1.485
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 148.5
        }]
    }
    "2560x1440@60" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 2.43168
            CONFIG.TX_PLL_TYPE QPLL1
            CONFIG.TX_REFCLK_FREQUENCY 121.584

            CONFIG.RX_LINE_RATE 2.43168
            CONFIG.RX_PLL_TYPE QPLL1
            CONFIG.RX_REFCLK_FREQUENCY 121.584
        }]
    }
    "1920x1080@120" -
    "3840x2160@30" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 2.97
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 148.5

            CONFIG.RX_LINE_RATE 2.97
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 148.5
        }]
    }
    "1920x1080@144" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 3.564
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 148.5

            CONFIG.RX_LINE_RATE 3.564
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 148.5
        }]
    }
    "2560x1440@120" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 4.86336
            CONFIG.TX_PLL_TYPE QPLL1
            CONFIG.TX_REFCLK_FREQUENCY 121.584

            CONFIG.RX_LINE_RATE 4.86336
            CONFIG.RX_PLL_TYPE QPLL1
            CONFIG.RX_REFCLK_FREQUENCY 121.584
        }]
    }
    "2560x1440@144" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 5.836032
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 121.584

            CONFIG.RX_LINE_RATE 5.836032
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 121.584
        }]
    }
    "1920x1080@240" -
    "3840x2160@60" {
        set GTWIZARD0_PROPERTIES [concat $GTWIZARD0_PROPERTIES {
            CONFIG.TX_LINE_RATE 5.94
            CONFIG.TX_PLL_TYPE QPLL0
            CONFIG.TX_REFCLK_FREQUENCY 148.5

            CONFIG.RX_LINE_RATE 5.94
            CONFIG.RX_PLL_TYPE QPLL0
            CONFIG.RX_REFCLK_FREQUENCY 148.5
        }]
    }
    default {
        error "Invalid video mode $RESOLUTION@$REFRESH_RATE"
    }
}

set_property -dict $GTWIZARD0_PROPERTIES [get_ips GTWizard0]
