set_location_assignment PIN_AM17 -to led[0]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[0]
set_location_assignment PIN_AH18 -to led[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[1]
set_location_assignment PIN_AJ18 -to led[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[2]
set_location_assignment PIN_AH17 -to led[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[3]
set_location_assignment PIN_AJ16 -to led[4]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[4]
set_location_assignment PIN_AK17 -to led[5]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[5]
set_location_assignment PIN_AK16 -to led[6]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[6]
set_location_assignment PIN_AK18 -to led[7]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[7]
set_location_assignment PIN_AL18 -to led[8]
set_instance_assignment -name IO_STANDARD "1.8 V" -to led[8]
